name: Bug Report
description: "Report a general library issue."
body:
  - type: markdown
    attributes:
      value: |
          Before submitting your report, [please ensure your Laravel version is still supported](https://laravel.com/docs/releases#support-policy).
          
          **Did you know? Most problems can be resolved by running 3 commands:**
          
          - `composer self-update`
          - `composer global update`
          - `brew upgrade`

          ... in fact, it's good to run these commands at least once a month!
          
          Alternatively, try to reboot your machine first to see if it solves your current issue.
  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the issue you are facing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Provide detailed steps to reproduce your issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Diagnosis
      description: Run `valet diagnose` and then paste the output here.
    validations:
      required: true
      

