Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  # Increase RAM to 2GB because Composer was going out of memory
  config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
  ["vmware_fusion", "vmware_workstation"].each do |vmware|
      config.vm.provider vmware do |v|
          v.vmx["memsize"] = 2048
      end
  end
  config.vm.provider "parallels" do |v|
      v.memory = 2048
  end

  config.vm.synced_folder "../../../../", "/home/vagrant/cpriego-valet-linux"

  config.vm.provision "shell" do |s|
    s.path = "provision.sh"
    s.privileged = false
    s.env = {
      VALET_ENVIRONMENT: ENV['VALET_ENVIRONMENT'] || "testing"
    }
  end
end
