Vagrant.configure("2") do |config|
  config.vm.box = "bento/fedora-26"

  config.vm.synced_folder "../../../../", "/home/vagrant/cpriego-valet-linux"

  config.vm.provision "shell" do |s|
    s.path = "provision.sh"
    s.privileged = false
    s.env = {
      VALET_ENVIRONMENT: ENV['VALET_ENVIRONMENT'] || "testing"
    }
  end
end
